add_subdirectory(bf16_tensor_cell_gemm)
add_subdirectory(aiu_async_copy)
add_subdirectory(aiu_gemm)
add_subdirectory(binary_partition_cg)
add_subdirectory(global_to_shmem_async_copy)
add_subdirectory(graph_conditional_nodes)
add_subdirectory(graph_memory_footprint)
add_subdirectory(graph_memory_nodes)
add_subdirectory(imma_tensor_cell_gemm)
add_subdirectory(new_delete)
add_subdirectory(power_iteration_graph)
add_subdirectory(simple_hggc_graphs)
add_subdirectory(tf32_tensor_cell_gemm)
# add_subdirectory(warp_aggregated_atomics_cg)
