add_subdirectory(assert)
add_subdirectory(async_event_timing)
add_subdirectory(atomic_intrinsics)
add_subdirectory(clock)
add_subdirectory(cooperative_sync)
add_subdirectory(cpp_template_kernels)
add_subdirectory(device_diagnostics)
add_subdirectory(driver_runtime_interop)
add_subdirectory(fp16_dot_product)
add_subdirectory(matrix_mul)
add_subdirectory(block_sort_merge)
add_subdirectory(mpi_ppu_dispatch)
add_subdirectory(multi_device_collab)
add_subdirectory(occupancy_calculator)
add_subdirectory(openmp_ppu_dispatch)
add_subdirectory(project_template)
add_subdirectory(stream_callback)
add_subdirectory(streams_concurrency)
add_subdirectory(unified_memory_models)
add_subdirectory(vector_add)
add_subdirectory(warp_vote_ops)
