add_subdirectory(convolution_separable)
add_subdirectory(ctx_management)
add_subdirectory(histogram)
add_subdirectory(inline_tix)
add_subdirectory(radix_sort_thrust)
add_subdirectory(scan)
add_subdirectory(spmv)
add_subdirectory(stream_compact)
add_subdirectory(stream_ordered_allocation)
add_subdirectory(warp_bitonic_sort)
add_subdirectory(warp_redux)
